@api = http://localhost:4000/api/exercise

GET {{api}}/1
###
# POST {{api}}
# Content-Type: application/json

# {
#     "name": "Salma",
#     "lastname": "Torres",
#     "email": "salma4@gmail.com",
#     "password": "951753",
#     "role_id": 2
# }