@api = http://localhost:4000/api/exercise
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsIm5hbWUiOiJJc2FhYyBNb250ZXMiLCJpYXQiOjE2MzI0MzEyOTMsImV4cCI6MTYzMjQzODQ5M30.IWa2kl7sj1aGsh8oF178GXWBG-IQR7pw41ItmpDAB70

GET {{api}}/1
x-token: {{token}}
###
POST {{api}}
x-token: {{token}}
Content-Type: application/json

{
    "name": "Barbell rows",
    "description": "This is one of the best barbell exercises to train your back",
    "image_name": "barbellRows.jpg",
    "muscleId": 1
}