@api = http://localhost:4000/api/exercise
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsIm5hbWUiOiJJc2FhYyIsInJvbGVfaWQiOjEsImlhdCI6MTYzMzI3ODA1OSwiZXhwIjoxNjMzMjg1MjU5fQ.xPlboqIwhpNVmDG3Xcm1JUE202jrXh_LWLeNcM2R1BI

GET {{api}}/1
x-token: {{token}}
###
POST {{api}}
x-token: {{token}}
Content-Type: application/json

{
    "name": "Barbell squats",
    "description": "Best leg exercise",
    "image_name": "barbellSquats.jpg",
    "muscleId": 2
}

###
DELETE  {{api}}/11
x-token: {{token}}