@api = http://localhost:4000/api/user

GET {{api}}
###

POST {{api}}
Content-Type: application/json

{
    "email": "pedor@gmail.com",
    "password": "741852"
}


### For admin module
POST {{api}}/new
Content-Type: application/json

{
    "name": "Pedro",
    "lastname": "Torres",
    "email": "pedor@gmail.com",
    "password": "741852",
    "role_id": 2
}

###
POST {{api}}/register
Content-Type: application/json

{
    "name": "Batman",
    "lastname": "Parker",
    "email": "batker8@gmail.com",
    "password": "123456"
}